#include "stdafx.h"
#include "VertexLayout.h"

#define FORMAT_RGBF32 DXGI_FORMAT_R32G32B32_FLOAT
#define FORMAT_RGBAF32 DXGI_FORMAT_R32G32B32A32_FLOAT
#define VERTEX_DATA D3D11_INPUT_PER_VERTEX_DATA
#define ALIGNED_ELEMENT D3D11_APPEND_ALIGNED_ELEMENT

D3D11_INPUT_ELEMENT_DESC INPUT_POSITION = { "POSITION", 0, FORMAT_RGBF32, 0, 0, VERTEX_DATA, 0 };
D3D11_INPUT_ELEMENT_DESC INPUT_COLOR = { "COLOR", 0, FORMAT_RGBAF32, 0, ALIGNED_ELEMENT, VERTEX_DATA, 0 };
D3D11_INPUT_ELEMENT_DESC INPUT_TEXCOORD = { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, ALIGNED_ELEMENT, VERTEX_DATA, 0 };

D3D11_INPUT_ELEMENT_DESC Vertex::Desc[] =
{
	INPUT_POSITION,
};

D3D11_INPUT_ELEMENT_DESC VertexColor::Desc[] =
{
	INPUT_POSITION,
	INPUT_COLOR,
};

D3D11_INPUT_ELEMENT_DESC VertexTexture::Desc[] =
{
	INPUT_POSITION,
	INPUT_TEXCOORD,
};
	
D3D11_INPUT_ELEMENT_DESC VertexTextureColor::Desc[] =
{
	INPUT_POSITION,
	INPUT_TEXCOORD,
	INPUT_COLOR,
};